{
    "chapterDetails": {
        "chapterId": <chapterDetails.chapterId>,
        "syllabusName": "<chapterDetails.syllabusName>",
        "subjectName": "<chapterDetails.subjectName>",
        "chapterNumber": <chapterDetails.chapterNum>,
        "subChapterNumber": <chapterDetails.subChapterNum>,
        "chapterName": "<chapterDetails.chapterName>",
        "scriptBody": "<chapterDetails.scriptBody>"
    },
    "notesElements": [<notesElements:{notesElement|
        {
        "noteElementId": <notesElement.notesElementId>,
        "elementType": "<notesElement.elementType>",
        "difficultyLevel": <notesElement.difficultyLevel>,
        "evalVars": <notesElement.evalVars>,
        "scriptBody": "<notesElement.scriptBody>",
        "learningStats": {
            "learningEfficiency": 0,
            "absLearningEfficiency": 0
        \},
        <notesElement.content>
   \}
    }; separator=",\n">]
}